### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by NeroBlackstone** [JuliaMusic/PianoFingering.jl#2]
- [x] PIG dataset loader
- [ ] midi to PIG without/with fingering
- [ ] musicxml to PIG without/with fingering
- [ ] support repeat measure
- [ ] more reward function improve
